name: Self-hosted runner (middle-man)

on:
  workflow_run:
    workflows: ["Self-hosted runner (push-caller)"]
    branches: ["main"]
    types: [completed]

jobs:
  run_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers (main)
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Checkout to [push-ci] and push
        # A more strict way to make sure`push-ci` is exactly the same as `main` at the push event commit.
        run: |
          git checkout -b push-ci
          git push -u origin push-ci --force
          echo bonjour
          sleep 3m 30s
          echo au revoir