name: Self-hosted runner (push)

on:
  workflow_run:
    workflows: ["Self-hosted runner (push-caller)"]
    branches: ["main", "bonbon-none"]
    types: [completed]
  push:
    branches:
      - bonbon-none

jobs:
  run_push_ci:

    name: Run Push CI
    runs-on: ubuntu-latest
    steps:

      - name: Run actual push CI
        run: echo "Run actual push CI"

      - name: Prepare custom ENV variables
        run: |
          CI_BRANCH_PUSH=${{ github.event.ref }}
          CI_BRANCH_WORKFLOW_RUN=${{ github.event.workflow_run.head_branch }}
          CI_SHA_PUSH=${{ github.event.head_commit.id }}
          CI_SHA_WORKFLOW_RUN=${{ github.event.workflow_run.head_sha }}
          CI_COMMIT_URL_PUSH=https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.head_commit.id }}
          CI_COMMIT_URL_WORKFLOW_RUN=https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.workflow_run.head_sha }}
          echo $CI_BRANCH_PUSH
          echo $CI_BRANCH_WORKFLOW_RUN
          echo $CI_SHA_PUSH
          echo $CI_SHA_WORKFLOW_RUN
          echo $CI_COMMIT_URL_PUSH
          echo $CI_COMMIT_URL_WORKFLOW_RUN          
          [[ ! -z "$CI_BRANCH_PUSH" ]] && echo "CI_BRANCH=$CI_BRANCH_PUSH" >> $GITHUB_ENV || echo "CI_BRANCH=$CI_BRANCH_WORKFLOW_RUN" >> $GITHUB_ENV
          [[ ! -z "$CI_SHA_PUSH" ]] && echo "CI_SHA=$CI_SHA_PUSH" >> $GITHUB_ENV || echo "CI_SHA=$CI_SHA_WORKFLOW_RUN" >> $GITHUB_ENV
          [[ ! -z "$CI_SHA_PUSH" ]] && echo "CI_COMMIT_URL=$CI_COMMIT_URL_PUSH" >> $GITHUB_ENV || echo "CI_COMMIT_URL=$CI_COMMIT_URL_WORKFLOW_RUN" >> $GITHUB_ENV

      - name: print prepared ENV variables
        run: |
          echo ${{ env.CI_BRANCH }}
          echo ${{ env.CI_SHA }}
          echo ${{ env.CI_COMMIT_URL }}

      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: print transformers after actions/checkout@v2
        run: |
          echo $(git branch --show-current)
          echo $(git log -n 1)

      - name: Update clone use prepared ENV variables
        run: |
          git fetch && git checkout ${{ env.CI_BRANCH }}
          echo $(git branch --show-current)
          echo $(git log -n 1)
          git checkout ${{ env.CI_SHA }}
          echo $(git branch --show-current)
          echo $(git log -n 1)

      - name: print transformers  after updating clone using prepared ENV variables
        run: |
          echo $(git branch --show-current)
          echo $(git log -n 1)

  send_results:
    name: Send results to webhook
    runs-on: ubuntu-latest
    if: always()
    needs: [run_push_ci]
    steps:

      - name: Prepare custom ENV variables
        run: |
          CI_SHA_PUSH=${{ github.event.head_commit.id }}
          CI_SHA_WORKFLOW_RUN=${{ github.event.workflow_run.head_sha }}
          echo $CI_SHA_PUSH
          echo $CI_SHA_WORKFLOW_RUN       
          [[ ! -z "$CI_SHA_PUSH" ]] && echo "CI_SHA=$CI_SHA_PUSH" >> $GITHUB_ENV || echo "CI_SHA=$CI_SHA_WORKFLOW_RUN" >> $GITHUB_ENV

      - name: print prepared ENV variables
        run: |
          echo ${{ env.CI_SHA }}

      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/download-artifact@v2

      - name: Send message to Slack
        env:
          CI_EVENT: push
          CI_TITLE_PUSH: ${{ github.event.head_commit.message }}
          CI_TITLE_WORKFLOW_RUN: ${{ github.event.workflow_run.head_commit.message }}
          CI_SHA: ${{ env.CI_SHA }}
        # We pass `needs.setup.outputs.matrix` as the argument. A processing in `notification_service.py` to change
        # `models/bert` to `models_bert` is required, as the artifact names use `_` instead of `/`.
        run: |
          echo $CI_EVENT
          echo $CI_SHA
          echo $CI_TITLE_PUSH
          echo $CI_TITLE_WORKFLOW_RUN
          python utils/notification_service.py
