# a Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - main

jobs:
  call_push_ci:
    name: Call Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          echo "${{ github.sha }}"
