name: Self-hosted runner (push)

on:
  workflow_run:
    workflows: ["Self-hosted runner (push-caller)"]
    branches: ["main", "bonbon"]
    types: [completed]

jobs:
  run_push_ci:

    name: Run Push CI
    runs-on: ubuntu-latest
    steps:

      - name: Run actual push CI
        run: echo "Run actual push CI"

      - name: print detailed information
        # For push even, we have `${{ github.event.head_commit.message }}` and `${{ github.event.head_commit.url }}`
        # For workflow_run, we need `${{ github.event.workflow_run.head_xxx ... }}`
        run: |
          echo "more info"
          echo ${{ github.sha }}
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.head_sha }}
          echo ${{ github.event.workflow_run.head_commit.url }}
          echo "done"

      - name: Prepare custom ENV variables
        # CI_COMMIT_URL=https://github.com/huggingface/transformers/commit/${{ github.event.workflow_run.head_sha }}
        # More general
        # CI_COMMIT_URL=https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.workflow_run.head_sha }}
        # [IMPORTANT] `echo "CI_SHA=$CI_SHA" >> $GITHUB_ENV` can't have new line character `\n`
        run: |
          CI_BRANCH=${{ github.event.workflow_run.head_branch }}
          CI_SHA=${{ github.event.workflow_run.head_sha }}
          CI_COMMIT_URL=https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.workflow_run.head_sha }}
          echo $CI_BRANCH
          echo $CI_SHA
          echo $CI_COMMIT_URL
          echo "CI_BRANCH=$CI_BRANCH" >> $GITHUB_ENV
          echo "CI_SHA=$CI_SHA" >> $GITHUB_ENV
          echo "CI_COMMIT_URL=$CI_COMMIT_URL" >> $GITHUB_ENV

      - name: print prepared ENV variables
        run: |
          echo ${{ env.CI_BRANCH }}
          echo ${{ env.CI_SHA }}

          echo ${{ env.CI_COMMIT_URL }}

      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: print transformers after actions/checkout@v2
        run: |
          echo $(git branch --show-current)
          echo $(git log -n 1)

#      - name: Update clone
#        run: |
#          git fetch && git checkout ${{ github.event.workflow_run.head_branch }}
#          echo $(git branch --show-current)
#          echo $(git log -n 1)
#          git checkout ${{ github.event.workflow_run.head_sha }}
#          echo $(git branch --show-current)
#          echo $(git log -n 1)
#
#      - name: print transformers after updating clone
#        run: |
#          echo $(git branch --show-current)
#          echo $(git log -n 1)

      - name: Update clone use prepared ENV variables
        run: |
          git fetch && git checkout ${{ env.CI_BRANCH }}
          echo $(git branch --show-current)
          echo $(git log -n 1)
          git checkout ${{ env.CI_SHA }}
          echo $(git branch --show-current)
          echo $(git log -n 1)

      - name: print transformers  after updating clone using prepared ENV variables
        run: |
          echo $(git branch --show-current)
          echo $(git log -n 1)

  send_results:
    name: Send results to webhook
    runs-on: ubuntu-latest
    if: always()
    needs: [run_push_ci]
    steps:

      - name: Prepare custom ENV variables
        # CI_COMMIT_URL=https://github.com/huggingface/transformers/commit/${{ github.event.workflow_run.head_sha }}
        # More general
        # CI_COMMIT_URL=https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.workflow_run.head_sha }}
        run: |
          CI_BRANCH=${{ github.event.workflow_run.head_branch }}
          CI_SHA=${{ github.event.workflow_run.head_sha }}
          CI_COMMIT_URL=https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.workflow_run.head_sha }}
          echo $CI_BRANCH
          echo $CI_SHA
          echo $CI_COMMIT_URL
          echo "CI_BRANCH=$CI_BRANCH" >> $GITHUB_ENV
          echo "CI_SHA=$CI_SHA" >> $GITHUB_ENV
          echo "CI_COMMIT_URL=$CI_COMMIT_URL" >> $GITHUB_ENV

      - name: print prepared ENV variables
        run: |
          echo ${{ env.CI_BRANCH }}
          echo ${{ env.CI_SHA }}
          echo ${{ env.CI_COMMIT_URL }} 

      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Update clone use prepared ENV variables
        run: |
          git fetch && git checkout ${{ env.CI_BRANCH }}
          echo $(git branch --show-current)
          echo $(git log -n 1)
          git checkout ${{ env.CI_SHA }}
          echo $(git branch --show-current)
          echo $(git log -n 1)

      - name: print transformers  after updating clone using prepared ENV variables
        run: |
          echo $(git branch --show-current)
          echo $(git log -n 1)

      - uses: actions/download-artifact@v2

      - name: Send message to Slack
        env:
          CI_EVENT: push
          CI_TITLE: ${{ github.event.workflow_run.head_commit.message }}
          CI_COMMIT_URL: ${{ env.CI_COMMIT_URL }}
        # We pass `needs.setup.outputs.matrix` as the argument. A processing in `notification_service.py` to change
        # `models/bert` to `models_bert` is required, as the artifact names use `_` instead of `/`.
        # python utils/notification_service.py
        run: |
          echo $CI_EVENT
          echo $CI_COMMIT_URL
          python utils/notification_service.py
