name: Self-hosted runner (push)

on:
  push:
    branches:
      - push-ci-none

jobs:
  setup:
    name: Setup (push-ci)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers (push-ci)
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
