# Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - main
      - bonbon

jobs:
  call_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers
        run: |
          echo "Trigger push CI via workflow_run"
          echo "commit message"
          echo ${{ github.event.head_commit.message }}
          echo "commit url"
          echo ${{ github.event.head_commit.url }}

      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: print transformers
        run: |
          echo $(git branch)
          echo $(git log -n 1)
          echo "OK"

      - name: Sleep
        run: sleep 3m