name: Self-hosted runner (push)

on:
  push:
    branches:
      - push-ci-none
  workflow_run:
    workflows: ["Self-hosted runner (push-caller)"]
    branches: ["main"]
    types: [completed]

jobs:
  setup:
    name: Setup (push-ci)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers (push-ci)
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
