# Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - main

jobs:
  call_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers
        run: |
          echo "Trigger push CI via workflow_run"
          echo "commit message"
          echo ${{ github.event.head_commit.message }}
          echo "commit url"
          echo ${{ github.event.head_commit.url }}