name: Self-hosted runner (push)

on:
  workflow_run:
    workflows: ["Self-hosted runner (push-caller)"]
    branches: ["main", "bonbon"]
    types: [completed]

jobs:
  run_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers
        run: echo "Trigger push CI via workflow_run"
      - name: print detailed information
        run: |
          echo "commit message"
          echo ${{ github.event.head_commit.message }}
          echo "commit url"
          echo ${{ github.event.head_commit.url }}
          echo "more info"
          echo ${{ github.event.workflow_run.action }}
          echo ${{ github.event.workflow_run.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.workflow_run.head_sha }}
          echo ${{ github.event.workflow_run.workflow_run.head_commit.message }}
          echo ${{ github.event.workflow_run.workflow_run.head_commit.url }}
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.head_sha }}
          echo ${{ github.event.workflow_run.head_commit.message }}
          echo ${{ github.event.workflow_run.head_commit.url }}