# Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - main

jobs:
  run_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers
        run: echo "Trigger push CI via workflow_run"